name: CI - Build & Type Check

on:
  # ✅ Chỉ chạy khi:
  # - Push vào main/dev (để kiểm tra sau merge)
  # - Hoặc mở / cập nhật PR vào main/dev (để review)
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: ⚡ Build changed packages only (with cache)
        run: pnpm turbo run build --filter=...[HEAD^1]

      - name: 🧠 Type Check
        run: pnpm turbo run type-check --filter=...[HEAD^1]

      - name: ✅ Verify build artifacts
        run: |
          echo "✅ Build completed successfully!"
          ls -la apps/web/.next || echo "⚠️ Web build output not found"
          ls -la apps/api/dist || echo "⚠️ API build output not found"

  comment:
    name: Post PR Status
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request'

    steps:
      - name: 💬 Post status comment
        uses: actions/github-script@v7
        with:
          script: |
            const buildStatus = '${{ needs.build.result }}';
            const emoji = buildStatus === 'success' ? '✅' : '❌';
            const message =
              buildStatus === 'success'
                ? '✨ All builds completed successfully!'
                : '⚠️ Build failed. Please fix before merging.';

            const comment = `## CI Build Status ${emoji}

            | Check | Status |
            |-------|--------|
            | Build & Type Check | ${emoji} ${buildStatus.toUpperCase()} |

            ${message}

            ---
            *Last updated: ${new Date().toUTCString()}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
